[package]

name = "session"
version = "0.1.0"
authors = ["Zach Pomerantz <zmp@umich.edu>"]

[lib]

name = "session"
path = "src/lib.rs"

[dependencies]
iron = "*"

[dependencies.iron-test]

git = "https://github.com/reem/iron-test.git"
